[package]
name = "olympus"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
# Temporary bypasses to not use the VPN
robotics_lib = { version = "0.1.22", path = "src/dependencies/Robotic-Lib" }
midgard = { version = "0.1.2", path = "src/dependencies/midgard" }