[package]
name = "olympus"
version = "0.1.0"
edition = "2021"
publish = ["kellnr"]

[dependencies]
robotics_lib = { version = "0.1.21", registry = "kellnr" }
rip_worldgenerator = { version = "0.5.48", registry = "kellnr" }
macroquad = "0.4"